###
name: Testing Workflow

on:
  workflow_run:
    workflows: ["Developer Workflow"]
    types:
      - completed
  push:
    branches:
      - Qtest


jobs:
  build:
    runs-on: qtest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Debug
        run: |
          pwd
          ls -la

      - name: Install backend dependencies
        run: |
          cd server
          pwd
          npm ci --verbose
          cp  /home/ubuntu/qtest-key/server/.env /home/ubuntu/qtest-runner/_work/BROMAG_BOOKS/BROMAG_BOOKS/server
          ls -la

      - name: Install frontend dependencies
        run: |
          cd client
          cp /home/ubuntu/qtest-key/client/.env /home/ubuntu/qtest-runner/_work/BROMAG_BOOKS/BROMAG_BOOKS/client
          npm ci --verbose
          ls -la

      - name: Build and test backend
        run: |
          cd server
          pm2 restart qtest || echo "Failed to restart index.js"
 
      - name: Build and test frontend
        run: |
          cd client
          npm run build
          sudo systemctl restart nginx


#  notify:
#    runs-on: ubuntu-latest
#    needs: deploy
#    steps:
#      - name: Send notification
#        run: echo "Testing branch deployment succeeded! Please review the changes and merge to production if no issues."
