name: checktheworkflow

on:
  push

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: pwd
        run: ls -al
      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: build
        run: |
        cd client
        npm ci --verbose
        npm run build
        ls
      
    