name: checktheworkflow

on:
  push

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: first job
        run: echo "hello world"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: pwd
        run: ls -al
      
    